application: build-a-blog
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /*
  script: main.app

- url: /blog
  script: main.app

-url: /newpost
  script: main.app

-url: /blog/<id:\d+>
  script: main.app

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
  
- name: jinja2
  version: latest
